@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<section class="mx-auto max-w-[1280px] px-5 py-14 lg:px-10 lg:py-20"><div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-primary">{{ strtoupper($user->getRoleNames()->first()) }} DASHBOARD</p><h1 class="mt-3 font-display text-4xl font-bold lg:text-5xl">Halo, {{ explode(' ',$user->name)[0] }}.</h1><p class="mt-3 text-on-surface-variant">Kelola seluruh aktivitas CasualHub dari satu tempat.</p></div><a href="{{ $user->hasRole('worker')?route('jobs.index'):route('jobs.manage') }}" class="btn-primary">{{ $user->hasRole('worker')?'Cari pekerjaan':'Posting lowongan' }}</a></div><div class="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($stats as $label=>$value)<div class="card"><p class="text-sm text-on-surface-variant">{{ $label }}</p><strong class="mt-3 block font-display text-3xl">{{ (str_contains(strtolower($label),'saldo')||str_contains(strtolower($label),'pembayaran'))?'Rp'.number_format($value,0,',','.'):$value }}</strong><div class="mt-5 h-1.5 rounded-full bg-primary-soft"><div class="h-full w-2/3 rounded-full bg-primary"></div></div></div>@endforeach</div><h2 class="mt-12 font-display text-2xl font-bold">Menu utama</h2><div class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
@if($user->hasRole('worker'))
@foreach([[route('jobs.my'),'bookmark','My Jobs','Shift aktif dan riwayat kerja'],[route('attendance.index'),'bolt','Shift Attendance','Check-in dan kehadiran'],[route('wallet.index'),'wallet','Wallet & Earnings','Saldo dan transaksi'],[route('profile.edit'),'person','My Profile','Profil, CV, dan portfolio'],[route('applications.index'),'description','Lamaran','Pantau status lamaran'],[route('reviews.index'),'star','Reviews','Reputasi dan ulasan'],[route('messages.index'),'messages','Messages','Percakapan perusahaan'],[route('notifications.index'),'notifications','Notifikasi','Pembaruan akun']] as $menu)<a href="{{ $menu[0] }}" class="card group !p-6 hover:-translate-y-1"><div class="grid size-12 place-items-center rounded-2xl bg-primary-soft text-primary"><x-icon name="{{ $menu[1] }}"/></div><h3 class="mt-5 font-display text-lg font-semibold group-hover:text-primary">{{ $menu[2] }}</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">{{ $menu[3] }}</p></a>@endforeach
@elseif($user->hasRole('company'))
@foreach([[route('jobs.manage'),'bookmark','Kelola Lowongan','Posting dan edit pekerjaan'],[route('applications.index'),'description','Daftar Pelamar','Review worker dan CV'],[route('wallet.index'),'wallet','Wallet & Payment','Saldo dan pembayaran'],[route('messages.index'),'messages','Messages','Percakapan worker'],[route('reviews.index'),'star','Reviews','Ulasan perusahaan'],[route('notifications.index'),'notifications','Notifikasi','Pembaruan platform'],[route('settings.index'),'person','Settings','Pengaturan akun'],[route('companies.show',$user->company),'storefront','Company Profile','Profil publik perusahaan']] as $menu)<a href="{{ $menu[0] }}" class="card group !p-6 hover:-translate-y-1"><div class="grid size-12 place-items-center rounded-2xl bg-primary-soft text-primary"><x-icon name="{{ $menu[1] }}"/></div><h3 class="mt-5 font-display text-lg font-semibold group-hover:text-primary">{{ $menu[2] }}</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">{{ $menu[3] }}</p></a>@endforeach
@else
@foreach([[route('jobs.manage'),'bookmark','Semua Lowongan','Moderasi pekerjaan'],[route('applications.index'),'description','Semua Lamaran','Pantau aktivitas'],[route('companies.index'),'storefront','Perusahaan','Direktori perusahaan'],[route('notifications.index'),'notifications','Notifikasi','Pembaruan platform'],[route('settings.index'),'person','Settings','Pengaturan akun'],[route('help.index'),'search','Help Center','Pusat bantuan']] as $menu)<a href="{{ $menu[0] }}" class="card group !p-6 hover:-translate-y-1"><div class="grid size-12 place-items-center rounded-2xl bg-primary-soft text-primary"><x-icon name="{{ $menu[1] }}"/></div><h3 class="mt-5 font-display text-lg font-semibold group-hover:text-primary">{{ $menu[2] }}</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">{{ $menu[3] }}</p></a>@endforeach
@endif
</div></section>
@endsection
