@extends('layouts.app')
@section('title', 'My Jobs')
@section('content')
<section class="mx-auto max-w-[1280px] px-5 py-14 lg:px-10 lg:py-20">
    <div class="flex flex-col justify-between gap-6 md:flex-row md:items-end">
        <div><p class="text-xs font-bold uppercase tracking-[.2em] text-primary">WORKER WORKSPACE</p><h1 class="mt-3 font-display text-4xl font-bold lg:text-5xl">My Jobs</h1><p class="mt-3 text-on-surface-variant">Kelola shift aktif, jadwal mendatang, dan riwayat pekerjaanmu.</p></div>
        <a href="{{ route('jobs.index') }}" class="btn-primary"><x-icon name="search" class="mr-2" />Cari pekerjaan</a>
    </div>

    <div class="mt-10 grid gap-5 sm:grid-cols-3"><div class="card"><p class="text-sm text-on-surface-variant">Pekerjaan aktif</p><strong class="mt-3 block font-display text-3xl">{{ $jobs->where('status','accepted')->count() }}</strong></div><div class="card"><p class="text-sm text-on-surface-variant">Pekerjaan selesai</p><strong class="mt-3 block font-display text-3xl">{{ $completedCount }}</strong></div><div class="card"><p class="text-sm text-on-surface-variant">Total penghasilan</p><strong class="mt-3 block font-display text-3xl">Rp{{ number_format($totalEarnings,0,',','.') }}</strong></div></div>

    @if($activeJob)
        <div class="mt-10 overflow-hidden rounded-[28px] bg-gradient-to-br from-secondary to-[#4f2933] p-7 text-white shadow-2xl lg:p-10"><div class="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div class="flex flex-wrap gap-3"><span class="rounded-full bg-[#007d7d] px-4 py-2 text-xs font-bold">SHIFT AKTIF</span><span class="rounded-full bg-white/10 px-4 py-2 text-xs">{{ $activeJob->job->category->name }}</span></div><h2 class="mt-6 font-display text-3xl font-bold">{{ $activeJob->job->title }}</h2><p class="mt-3 text-white/70">{{ $activeJob->job->company->name }} &middot; {{ $activeJob->job->location }}</p><div class="mt-7 grid gap-4 text-sm sm:grid-cols-3"><div><span class="block text-white/50">Tanggal</span><b class="mt-1 block">{{ $activeJob->job->starts_at->format('d M') }} - {{ $activeJob->job->ends_at->format('d M Y') }}</b></div><div><span class="block text-white/50">Rate</span><b class="mt-1 block">Rp{{ number_format($activeJob->job->daily_rate,0,',','.') }}/hari</b></div><div><span class="block text-white/50">Status</span><b class="mt-1 block">Diterima</b></div></div></div><div class="rounded-3xl bg-white/10 p-6 text-center backdrop-blur"><span class="text-sm text-white/60">Mulai dalam</span><strong class="mt-2 block font-display text-4xl">{{ max(0,now()->diffInDays($activeJob->job->starts_at,false)) }}</strong><span class="text-sm">hari</span><a href="{{ route('jobs.show',$activeJob->job) }}" class="mt-5 block rounded-full bg-white px-6 py-3 text-sm font-bold text-secondary">Lihat detail</a></div></div></div>
    @endif

    <div class="mt-12"><div class="flex items-center justify-between"><h2 class="font-display text-2xl font-bold">Semua pekerjaan</h2><span class="text-sm text-on-surface-variant">{{ $jobs->total() }} pekerjaan</span></div><div class="mt-6 grid gap-5 lg:grid-cols-2">@forelse($jobs as $application)<article class="rounded-3xl bg-white p-6 shadow-[0_24px_60px_-36px_rgba(18,18,18,.3)]"><div class="flex items-start justify-between gap-4"><div class="grid size-14 shrink-0 place-items-center rounded-2xl bg-primary-soft font-display text-xl font-bold text-primary">{{ strtoupper(substr($application->job->company->name,0,1)) }}</div><span class="badge {{ $application->status==='completed' ? '!bg-surface-container !text-neutral' : '' }}">{{ strtoupper($application->status) }}</span></div><h3 class="mt-5 font-display text-xl font-semibold">{{ $application->job->title }}</h3><p class="mt-2 text-sm text-on-surface-variant">{{ $application->job->company->name }} &middot; {{ $application->job->location }}</p><div class="mt-5 grid grid-cols-2 gap-3 rounded-2xl bg-surface-low p-4 text-sm"><div><span class="block text-xs text-on-surface-variant">Jadwal</span><b>{{ $application->job->starts_at->format('d M Y') }}</b></div><div><span class="block text-xs text-on-surface-variant">Kehadiran</span><b>{{ $application->attendances->count() }} catatan</b></div></div><div class="mt-5 flex items-center justify-between"><strong>Rp{{ number_format($application->job->daily_rate,0,',','.') }}/hari</strong><a href="{{ route('jobs.show',$application->job) }}" class="font-bold text-primary">Detail &rarr;</a></div></article>@empty<div class="card col-span-full py-20 text-center"><x-icon name="description" class="mx-auto size-12 text-primary" /><h3 class="mt-5 font-display text-2xl font-bold">Belum ada pekerjaan</h3><p class="mt-2 text-on-surface-variant">Pekerjaan yang sudah diterima akan tampil di halaman ini.</p><a href="{{ route('jobs.index') }}" class="btn-primary mt-7">Cari lowongan</a></div>@endforelse</div><div class="mt-10">{{ $jobs->links() }}</div></div>
</section>
@endsection

