@extends('layouts.app')
@section('title','Wallet & Earnings')
@section('content')
<section class="mx-auto max-w-[1200px] px-5 py-12 lg:px-10 lg:py-16">
<p class="text-xs font-bold uppercase tracking-[.2em] text-primary">Finance</p><h1 class="mt-3 font-display text-4xl font-bold lg:text-5xl">Wallet & Earnings</h1><p class="mt-3 text-on-surface-variant">Saldo hanya berubah dari pembayaran dan penarikan yang tercatat.</p>
<div class="mt-10 grid gap-6 lg:grid-cols-[1fr_1.4fr]"><div class="rounded-[30px] bg-gradient-to-br from-primary to-[#6e001f] p-8 text-white shadow-2xl"><p class="text-sm text-white/70">Saldo tersedia</p><strong class="mt-4 block font-display text-4xl">Rp{{ number_format($wallet->balance,0,',','.') }}</strong><div class="mt-10 border-t border-white/20 pt-5 text-sm"><div class="flex justify-between"><span>Saldo menunggu pembayaran</span><b>Rp{{ number_format($wallet->pending_balance,0,',','.') }}</b></div></div></div><form method="POST" action="{{ route('wallet.withdraw') }}" class="card">@csrf<h2 class="font-display text-xl font-bold">Tarik saldo</h2><p class="mt-2 text-sm text-on-surface-variant">Minimum Rp50.000. Setiap penarikan tercatat di riwayat.</p><label class="label mt-6" for="amount">Jumlah penarikan</label><input class="input" id="amount" name="amount" type="number" min="50000" step="1000" max="{{ (int)$wallet->balance }}" placeholder="Contoh: 100000" required><button class="btn-primary mt-5" type="submit" @disabled($wallet->balance < 50000)>Tarik saldo</button></form></div>
<div class="mt-12"><h2 class="font-display text-2xl font-bold">Riwayat transaksi</h2><div class="mt-5 overflow-hidden rounded-3xl bg-white">@forelse($transactions as $transaction)<div class="flex items-center justify-between gap-4 border-b border-black/5 p-5 last:border-0"><div><b>{{ $transaction->description }}</b><p class="mt-1 text-xs text-on-surface-variant">{{ $transaction->created_at->format('d M Y, H:i') }} · {{ $transaction->reference }}</p></div><strong class="{{ $transaction->type==='credit'?'text-[#007d68]':'text-primary' }}">{{ $transaction->type==='credit'?'+':'-' }} Rp{{ number_format($transaction->amount,0,',','.') }}</strong></div>@empty<div class="p-14 text-center text-on-surface-variant">Belum ada transaksi wallet.</div>@endforelse</div><div class="mt-8">{{ $transactions->links() }}</div></div>
</section>
@endsection
