@extends('layouts.app')
@section('title','Shift Attendance')
@section('content')
@php
    $todayAttendance = $applications->getCollection()->flatMap->attendances->first(fn($item) => $item->work_date->isToday());
    $active = $todayAttendance?->application ?? $applications->firstWhere('status','accepted');
@endphp
<section class="mx-auto max-w-[1200px] px-5 py-12 lg:px-10 lg:py-16">
    <p class="text-xs font-bold uppercase tracking-[.2em] text-primary">Attendance</p><h1 class="mt-3 font-display text-4xl font-bold lg:text-5xl">Shift Attendance</h1><p class="mt-3 text-on-surface-variant">Check-in hanya aktif pada tanggal shift yang sudah dijadwalkan.</p>
    @if($active)
    <div class="mt-10 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><div class="rounded-[30px] bg-gradient-to-br from-secondary to-[#4f2933] p-7 text-white sm:p-9"><span class="rounded-full bg-[#007d7d] px-4 py-2 text-xs font-bold">{{ $todayAttendance ? 'SHIFT HARI INI' : 'SHIFT TERJADWAL' }}</span><p class="mt-10 text-white/60">{{ $todayAttendance?->work_date->format('d F Y') ?? $active->job->starts_at->format('d F Y') }}</p><h2 class="mt-2 font-display text-3xl font-bold">{{ $active->job->title }}</h2><p class="mt-2 text-white/70">{{ $active->job->company->name }} Â· {{ $active->job->location }}</p><div class="mt-9 rounded-2xl bg-white/10 p-5"><p class="text-xs uppercase tracking-widest text-white/60">Catatan waktu</p><strong class="mt-2 block font-display text-3xl">{{ $todayAttendance?->clock_in_at?->format('H:i') ?? '--:--' }} â€” {{ $todayAttendance?->clock_out_at?->format('H:i') ?? '--:--' }}</strong></div><div class="mt-7 flex flex-wrap gap-3">@if($todayAttendance && !$todayAttendance->clock_in_at)<form method="POST" action="{{ route('attendance.clock-in',$todayAttendance) }}">@csrf<button class="btn-primary" type="submit">Check In</button></form>@elseif($todayAttendance && !$todayAttendance->clock_out_at)<form method="POST" action="{{ route('attendance.clock-out',$todayAttendance) }}">@csrf<button class="btn-primary" type="submit">Check Out</button></form>@elseif($todayAttendance)<span class="rounded-xl bg-white px-5 py-3 font-bold text-secondary">Shift selesai</span>@else<span class="rounded-xl bg-white/10 px-5 py-3 text-sm">Belum ada shift untuk hari ini</span>@endif</div></div><div class="card"><h3 class="font-display text-xl font-bold">Detail shift</h3><dl class="mt-7 space-y-5"><div><dt class="text-sm text-on-surface-variant">Jadwal kerja</dt><dd class="mt-1 font-semibold">{{ $active->job->starts_at->format('d M Y, H:i') }} â€“ {{ $active->job->ends_at->format('d M Y, H:i') }}</dd></div><div><dt class="text-sm text-on-surface-variant">Lokasi</dt><dd class="mt-1 font-semibold">{{ $active->job->location }}</dd></div><div><dt class="text-sm text-on-surface-variant">Total jadwal</dt><dd class="mt-1 font-semibold">{{ $active->attendances->count() }} hari</dd></div></dl></div></div>
    @else<div class="card mt-10 py-16 text-center"><h2 class="font-display text-2xl font-bold">Tidak ada shift aktif</h2><p class="mt-2 text-on-surface-variant">Shift muncul otomatis setelah lamaran diterima.</p><a href="{{ route('jobs.index') }}" class="btn-primary mt-6">Cari pekerjaan</a></div>@endif
    <div class="mt-12"><h2 class="font-display text-2xl font-bold">Riwayat dan jadwal</h2><div class="mt-5 space-y-4">@forelse($applications as $application) @foreach($application->attendances as $attendance)<div class="flex flex-col justify-between gap-4 rounded-2xl bg-white p-5 sm:flex-row sm:items-center"><div><b>{{ $application->job->title }}</b><p class="mt-1 text-sm text-on-surface-variant">{{ $attendance->work_date->format('d M Y') }} Â· {{ $application->job->company->name }}</p></div><div class="text-sm"><span class="badge">{{ ucfirst($attendance->status) }}</span><span class="ml-4">{{ $attendance->clock_in_at?->format('H:i') ?: '--:--' }} â€“ {{ $attendance->clock_out_at?->format('H:i') ?: '--:--' }}</span></div></div>@endforeach @empty<div class="card text-center text-on-surface-variant">Belum ada riwayat.</div>@endforelse</div><div class="mt-8">{{ $applications->links() }}</div></div>
</section>
@endsection

